#
# SE Mod Helpers - build script configuration file
#
# Include this file in your mod's top-level directory.

# `mod_name` is inferred from the location of this file, but can be specified
#mod_name: MyAwesomeMod

# If your code is organized as usual in a flat structure like:
#
# ModSourceFolder
#   - Data
#       - Scripts
#   - Models
#   - Textures
#
# Then `has_modules` should be false. This is default.
#
# If your code is organized into modules, i.e.
#
# ModSourceFolder
#   - Module1
#       - Data
#           - Scripts
#       - Models
#       - Textures
#   - Module2
#       - Data
#       - Scripts
#       - Textures
#   ... etc ...
#
# then `has_modules` should be true.
#
# Note scripts can live under Data (as usual) or at the top of the tree along
# with Models, Textures, etc
#has_modules: true

# Specify the various distributions you'd like to create in the SE Mods folder
# Distributes besides `production` require a suffix to append to the mod name
# when building their path. If one isn't provided its key will be used.
# Distributions may optionally specify a list of Compilation Symbols to remove
# from their '.cs' files.
distributions:
   development:
      suffix: " Dev"
   production:
      compile_symbols_to_remove:
        - DEBUG

# the path to SE's client-side mods folder
# this will be automatically inferred from %APPDATA%% unless provided below
#se_mods_dir: 'C:\Users\UserName\AppData\Roaming\SpaceEngineers\Mods'

# if mwm_builder_path points to MwmBuilder.exe, models will be built
#mwm_builder_path: 'C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Tools\MwmBuilder\MwmBuilder.exe'
